events {
	worker_connections 768;
	# multi_accept on;
}

http {
	server {
		listen 443 ssl;
		ssl_protocols TLSv1.2 TLSv1.3;
		ssl_certificate /etc/nginx/tls/server.crt;
		ssl_certificate_key /etc/nginx/tls/server.key;
    		location / {
			root /var/www/html;
			index index.nginx-debian.html;
		    }
		location ~ \.php$ {
			include snippets/fastcgi-php.conf;
			fastcgi_pass wordpress:9000;
		    # fastcgi_param SCRIPT_FILENAME /home/www/scripts/php$fastcgi_script_name;
		    # fastcgi_param QUERY_STRING    $query_string;
		    # fastcgi_param REQUEST_METHOD  $request_method;
		    # fastcgi_param CONTENT_TYPE    $content_type;
		    # fastcgi_param CONTENT_LENGTH  $content_length;
		}
	}
	sendfile on;
	ssl_protocols TLSv1.2 TLSv1.3; # Dropping SSLv3, ref: POODLE
	ssl_prefer_server_ciphers on;
	access_log /var/log/nginx/access.log;
}
