services:
  nginx:
    image: nginx-image
    networks:
      - inceptions
    container_name: nginx-container
    ports:
      - "443:443"
    build: ./requirements/nginx 
    volumes:
      - wordpress-volume:/var/www/html

  wordpress:
    image: wordpress-image
    networks:
      - inceptions
    container_name: wordpress-container
    ports:
      - "9000:9000"
    environment:
      WORDPRESS_DB_HOST: mariaDB:${PORT_DB_TO_WORDPRESS}
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${PASSWORD}
      WORDPRESS_DB_NAME: ${DB_NAME}
    build: ./requirements/wordpress
    command: docker volume create wordpress-volume
    volumes:
      - wordpress-volume:/var/www/html
    depends_on:
      - mariaDB

  mariaDB:
     image: mariadb-image
     networks:
       - inceptions
     container_name: mariadb-container
     build: ./requirements/mariadb
     volumes:
       - mariadb-volume:/var/lib/mysql
     environment:
       - MARIADB_ROOT_PASSWORD= ${ROOT_PASS}
       - MARIADB_DATABASE= ${DB_NAME}
       - MARIADB_USER= ${DB_USER}
       - MARIADB_PASSWORD= ${PASSWORD}
     ports:
       - "4444:3306"

volumes:
  mariadb-volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/lud-adam/data/mariadb-volume
  wordpress-volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/lud-adam/data/wordpress-volume

networks:
  inceptions:
